config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  get "/sign-up" => 'registrations#new', as: :signup
  post "/sign-up" => 'registrations#create'
  get "/sign-in" => 'sessions#new', as: :signin
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy', as: :signout

  root 'welcome#index'
    get '/' => 'pages#index'
    get '/about' => 'about#index'
    get '/terms' => 'terms#show'
    get '/faq' => 'faq#index'

end

app/models/membership.rb
class Membership < ActiveRecord::Base

#sets member to 0 and owner to 1 in the database
enum role: [:member, :owner]
belongs_to :user
belongs_to :project

validates :role, presence: true
validates :user_id, presence: true
validate :duplication, on: :create

  def duplication
    if user_id
      if project.users.find_by_id(user_id)
        errors[:base] << "User has already been added to this project"
      end
    end
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_project
  before_action :set_memberships
  before_action :set_project_access
  before_action :redirect_non_owners, only: [:new, :create, :edit, :update]
  layout "internal"

  def index
    @membership = Membership.new
  end

  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.new(membership_params)
    @membership.project_id = @project.id
    if @membership.save
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was successfully added"
    else
      render :index
    end
  end

  def update
    @membership = Membership.find(params[:id])
    if @membership.update(membership_params)
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was successfully updated"
    else
      render :index
  end
  end

  def destroy
    @membership = Membership.find(params[:id])
    if @membership.user_id == current_user.id || current_user.admin?
      if @membership.project.users.count != 1
        if @membership.destroy
          if @membership.user_id == current_user.id
            redirect_to projects_path, notice: "#{@membership.user.full_name} was successfully removed"
          else
            redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was successfully removed"
          end
        end
      else
        redirect_to project_memberships_path(@project, error: "Projects much have at least one owner")
      end
    end
  end

private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_memberships
    @memberships = @project.memberships
  end

  def membership_params
    params.require(:membership).permit(:user_id, :project_id, :role)
  end

end

app/views/memberships/index.html.erb
<h1 class = "page-header"><%=@project.name + " :Manage Members"%></h1>

<ol class= 'breadcrumb'>
  <li><a href= '/projects'>Projects</a></li>
  <li><%=link_to @project.name, project_path(@project)%></li>
  <li class='active'>Memberships</li>
</ol>

<% if current_user.admin || current_user.memberships.find_by(project_id: @project.id).role == "owner" %>
  <%= render partial: "shared/errors", locals: {object: @membership} %>
  <% if params[:error] %>
  <div id="error_explanation" class= "col-md-offset-1 col-md-10 alert alert-danger">
    <ul>
      <%=params[:error]%>
    </ul>
  </div>
  <% end %>
  <div class="row">
    <div class= "col-md-12">
      <div class= "well form-inline">
        <%= form_for [@project, @membership] do |f|%>
            <%= f.collection_select(:user_id, User.all, :id, :full_name, {prompt: "Please select a user..."}, class: "form-control")%>
            <%= f.select(:role, [["Member", :member],["Owner", :owner]],  {prompt: "this is a blank"}, class: "form-control")%>
            <%= f.submit "Add New Member", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

  <table>
    <tbody>
      <% @memberships.each do |membership|%>
        <tr>
          <td> <%= link_to membership.user.full_name, user_path(membership.user)%> </td>
          <td class= "form-inline">

            <%= form_for [@project, membership], action: :update do |f|%>
            <%= f.select(:role, [["Member", :member],["Owner", :owner] ], {blank: "this is a blank"} , class: "form-control")%>
            <%= f.submit class: "btn btn-primary"%>
            <% end  %>
          </td>
          <td>
            <%= link_to '', project_membership_path(@project, membership), class: 'glyphicon glyphicon-remove ', id: 'ex',  method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <%end %>
    </tbody>
  </table>
<% else %>
  <table class = "table table-striped table-hover">
    <tbody>
      <% @memberships.each do |membership| %>
        <tr>
          <td>
            <%= link_to membership.user.full_name, user_path(membership.user) %>
          </td>
          <td>
            <%= membership.role %>
          </td>
          <% if membership.user_id == current_user.id %>
            <td>
              <%= link_to '', project_membership_path(@project, membership), class: 'glyphicon glyphicon-remove ', id: 'ex',  method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          <% else %>
            <td>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>