config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  get "/sign-up" => 'registrations#new', as: :signup
  post "/sign-up" => 'registrations#create'
  get "/sign-in" => 'sessions#new', as: :signin
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy', as: :signout

  root 'welcome#index'
    get '/' => 'pages#index'
    get '/about' => 'about#index'
    get '/terms' => 'terms#show'
    get '/faq' => 'faq#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :description, presence: true
  belongs_to :project
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authorize
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  before_action :set_project_access
  layout "internal"


  def index
    @tasks = Task.all
    @project = Project.find(params[:project_id])
  end


  def show
  @comments = @task.comments
  @comment = Comment.new
  end


  def new
    @task = Task.new
  end


  def edit
  end


  def create
    @task = Task.new(task_params)
    @task.project_id = @project.id
    @task.task_completed = false
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :task_completed, :due_date)
    end
end

app/views/tasks/_form.html.erb
<%= form_for [@project ,@task], html:{class: "form-horizontal"} do |f| %>
<%= render partial: "shared/errors", locals: {object: @task} %>

    <div class= "form-group">
      <%= f.label :description, class: "control-label col-md-2" %>
      <div class= "form-controls col-md-4">
        <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :due_date, class: "control-label col-md-2" %>
      <%= f.date_select :due_date %>
    </div>
    
    <% unless @task.new_record? %>
    <div class="form-group">
      <%= f.label :task_completed, class: "control-label col-md-2" %>
      <%= f.check_box :task_completed %>
    </div>
    <% end %>
    <div class="form-group">
      <div class = "col-md-offset-2 col-md-4">
        <% if path = @task.new_record? %>
        <%= f.submit "Create Task", class: "btn btn-primary"  %>
        <% else %>
        <%= f.submit "Update Task", class: "btn btn-primary"  %>
        <% end %>
        <%= link_to "Cancel", project_tasks_path(@project), class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class= "page-header">Editing Task</h1>
<ol class= "breadcrumb">
  <li> <%=link_to "Projects", projects_path%></li>
  <li> <%= link_to @project.name, project_tasks_path(@project) %></li>
  <li class="active"><%= link_to @task.description, project_task_path(@project, @task) %> </li>
  <li class="active"><%=@task.description%></li>
</ol>


<%= render 'form' %>

app/views/tasks/index.html.erb
<h1 class = "page-header"><%= "Tasks for " + @project.name %>
  <%= link_to 'Delete', project_path(@project), class: "btn btn-danger pull-right", method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-info pull-right'%>
</h1>
    <ol class= 'breadcrumb'>
      <li> <%= link_to "Projects", projects_path%> </li>
      <li> <%= link_to @project.name, project_path(@project)%> </li>
      <li class='active'>Tasks</li>
    </ol>

    <table class = "table table-striped table-hover">
      <thead>
        <tr>
          <th>Description</th>
          <th>Completed</th>
          <th>Due Date</th>
          <th> <%= link_to "Add Task", new_project_task_path(@project), class: "btn btn-primary pull-right" %></th>
        </tr>
      </thead>
      <tbody>
        <% @project.tasks.each do |task| %>
        <tr>
          <td> <%=link_to task.description, project_task_path(@project, task)%> <a class="badge"> <%= task.comments.count %> </a></td>
          <td> <%= task.task_completed %></td>
          <td><%= task.due_date.strftime"%m/%d/%y" %> </td>
          <td class= "text-right">
            <%= link_to 'Edit Task', edit_project_task_path(@project, task), class: 'btn btn-info'%>
            <%= link_to '', project_task_path(@project, task), class: 'glyphicon glyphicon-remove', id: 'ex',  method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/tasks/new.html.erb
<h1 class="page-header"> New Task</h1>
<ol class= "breadcrumb">
  <li> <%=link_to "Projects", projects_path%></li>
  <li> <%= link_to @project.name, project_tasks_path(@project) %></li>
  <li class="active">New Task</li>
</ol>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1 class="page-header"> <%="Task: " + @task.description %>
<a class= 'btn btn-info pull-right' <%= link_to 'Edit', edit_project_task_path(@project, @task) %>
</h1>
<ol class= "breadcrumb">
  <li> <%= link_to "Projects", projects_path%></li>
  <li> <%= link_to @project.name, project_path(@project) %></li>
  <li> <%= link_to "Tasks", project_tasks_path(@project) %></li>
  <li class="active"><%=@task.description%></li>
</ol>

<dl class="dl-horizontal">
  <dt>Due Date</dt>
  <dd> <%= @task.due_date %></dd>
  <dt>Completed</dt>
  <dd> <%= @task.task_completed %></dd>
</dl>

<h4>Comments</h4>

<% @comments.each do |comment| %>
<div class= "row">
  <div class= "col-md-3">
    <% if comment.user_id == nil %>
      (deleted user)<br>
    <% else %>
      <%= link_to comment.user.full_name, user_path(comment.user)%><br>
    <% end %>
      <a class= "text-muted"><%= time_ago_in_words(comment.created_at) + " ago"%></a>
  </div>
  <div class= "col-md-9">
    <%= comment.description %>
  </div>
</div>
<% end %>



<div class= "row">
  <div class = "col-md-offset-3">
    <%= form_for [@project, @task, @comment] do |f| %>
      <%# f.label :description %>
      <div class = "form-group col-md-9">
        <%= f.text_area :description, size: "90%", class: "form-control" %><br>
        <%= f.submit "Add Comment", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>