config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  get "/sign-up" => 'registrations#new', as: :signup
  post "/sign-up" => 'registrations#create'
  get "/sign-in" => 'sessions#new', as: :signin
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy', as: :signout

  root 'welcome#index'
    get '/' => 'pages#index'
    get '/about' => 'about#index'
    get '/terms' => 'terms#show'
    get '/faq' => 'faq#index'

end

app/models/project.rb
class Project <ActiveRecord::Base
validates :name, presence: true
has_many :tasks, dependent: :destroy
has_many :memberships
has_many :users, through: :memberships
end

app/controllers/projects_controller.rb
class ProjectsController<ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  before_action :set_project_access, only: [:show, :edit, :update, :destroy]
  before_action :redirect_non_owners, only: [:edit, :update, :destroy]
  layout "internal"

  def index
    if current_user.admin?
      @projects = Project.all
    else
      @projects = current_user.projects
    end
  end

  def show
    @tasks = @project.tasks
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      Membership.new(user_id: current_user.id, project_id: @project.id, role: :owner).save
      redirect_to project_tasks_path(@project), notice: 'Project was successfully created'
    else
    render :new
    end
  end

  def edit
  end

  def update
  if @project.update(project_params)
    redirect_to project_tasks_path(@project), notice: 'Project was successfully updated'
  else
    render :edit
  end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end

end

app/views/projects/_form.html.erb
<%= form_for @project, html:{class: "form-horizontal"} do |f| %>
  <%= render partial: "shared/errors", locals: {object: @project} %>


  <div class= "col-md-12">
  </div>

    <div class= "form-group">
      <%= f.label :name, class: "control-label col-md-2" %>
      <div class= "form-controls col-md-4">
        <%= f.text_field :name, class: "form-control col-md-4" %>
      </div>
    </div>
    <div class="form-group">
      <div class = "col-md-offset-2 col-md-4">
        <% if path = @project.new_record? %>
        <%= f.submit "Create Project", class: "btn btn-primary"  %>
        <% else %>
        <%= f.submit "Update Project", class: "btn btn-primary"  %>
        <a class= 'btn btn-danger' <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <%= link_to "Cancel", "/projects", class: "btn btn-default" %>
        </div>
      </div>
    <% end %>

app/views/projects/edit.html.erb
<h1 class= 'page-header'>Editing</h1>
<ol class= 'breadcrumb'>
  <li><a href='/projects'>Projects</a></li>
  <li class='active'><%= link_to @project.name, project_tasks_path(@project)%></li>
  <li class='active'><%=@project.name%></li>
</ol>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1 class="page-header"> Projects
  <a class='btn pull-right btn-info' href=/projects/new> New Project</a>
</h1>
<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td ><%= link_to "#{project.name}", project_path(project), id: "clickme"%></td>
        <td>
          <%= project.tasks.count%>
        </td>
        <% if current_user.memberships.find_by(project_id: project.id) || current_user.admin?%>
          <% if current_user.admin? || current_user.memberships.find_by(project_id: project.id).role == "owner" %>
            <td class= "text-right">
              <a class= 'btn btn-info' <%= link_to 'Edit', edit_project_path(project) %>
            </td>
          <% else %>
            <td></td>
          <% end %>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1 class="page-header"> New Project</h1>
<ol class= "breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li class="active">New Project</li>
</ol>


<%= render 'form' %>

app/views/projects/show.html.erb
<h1 class = "page-header"><%=@project.name %>
  <% if  current_user.memberships.find_by(project_id: @project.id) || current_user.admin%>
    <% if current_user.admin? || current_user.memberships.find_by(project_id: @project.id).role == "owner" %>
      <a class= 'btn btn-info pull-right' <%= link_to 'Edit', edit_project_path(@project)%>
    <% end %>
  <% end %>
</h1>
<ol class= 'breadcrumb'>
  <li><a href= '/projects'>Projects</a></li>
  <li class='active'><%=@project.name%></li>
</ol>
<%= link_to "#{pluralize(@project.tasks.count, "Task")}", project_tasks_path(@project) %>
<br>
<%= link_to "#{pluralize(@project.memberships.count, "Membership")}", project_memberships_path(@project) %>
<% if current_user.memberships.find_by(project_id: @project.id) || current_user.admin%>
  <% if current_user.admin? || current_user.memberships.find_by(project_id: @project.id).role == "owner" %>
    <div class = "row">
      <div class = "col-md-12">
        <div class= "well">
          <h4>Delete</h4>
          <p>
            <%= "Deleting this project will also delete #{ pluralize(@project.memberships.count, "Membership")}, #{ pluralize(@project.tasks.count, "Task")}, and associated comments." %>
          </p>
          <a class= 'btn btn-danger' <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } %>    </div>
      </div>
    </div>
  <% end %>
<% end %>