config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  get "/sign-up" => 'registrations#new', as: :signup
  post "/sign-up" => 'registrations#create'
  get "/sign-in" => 'sessions#new', as: :signin
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy', as: :signout

  root 'welcome#index'
    get '/' => 'pages#index'
    get '/about' => 'about#index'
    get '/terms' => 'terms#show'
    get '/faq' => 'faq#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = favicon_link_tag 'favicon.ico'
    %a{:id => "top"}
    %title GCampFinneganHewitt
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %a.navbar-brand{:href => "/"} gCamp
        .ul-nav.navbar-nav.navbar-right.nav
          - if current_user
            %li
              = link_to "#{current_user.full_name}", user_path(current_user)
            %li
              = link_to "Sign Out", signout_path
          - else
            %li
              = link_to "Sign Up", signup_path
            %li
              = link_to "Sign In", signin_path
    .container

      - flash.each do |type, message|
        - if type == "notice"
          %b
            %center
              .alert.alert-success= message
        - elsif type == "alert"
          %b
            %center
              .alert.alert-danger= message.html_safe

      = yield
    .container
      .page-footer
        .row
          .col-xs-10

            %a.button{:href => "/about"} About
            |
            = link_to "Terms", terms_path
            |
            %a.button{:href => "/faq"} FAQ
            |
            -# %a.button{:href => "/tasks"} Tasks
            -# |
            = link_to "Users", users_path
            |
            = link_to "Projects", projects_path

          .col-xs-2{:align => "right"}
            =link_to(image_tag("linked_in-f852478f8950eb3fca3367cb545aaa52.jpg", class: "img-footer"), "https://linkedin.com/pub/finnegan-hewitt/71/94a/632")
            =link_to(image_tag("GitHub-de8164cc6a609537cfdab331e002ebb3.png", class: "img-footer"), "https://github.com/FBH037")
            =link_to(image_tag("Twitter-0c8c529fb7181e05ab5c30416e3a70fa.png", class: "img-footer"), "https://twitter.com/@fbhewitt")
            =link_to(image_tag("galvanize-g-b3da24895ed7d4fd33c43d9226c16242.png", class: "img-footer"), "https://students.gschool.it/students/203")

            %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"}
            -# %script{:src => "../../dist/js/bootstrap.min.js"}
            -# %script{:src => "../../assets/js/ie10-viewport-bug-workaround.js"}

app/views/layouts/internal.html.haml
!!!
%html
  %head
    = favicon_link_tag 'favicon.ico'
    %a{:id => "top"}
    %title GCampFinneganHewitt
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %a.navbar-brand{:href => projects_path} gCamp
        .ul-nav.navbar-nav.nav
          %li.dropdown.ul-nav
            %a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"}
              Projects
              %b.caret
            %ul.dropdown-menu{"role" => "menu"}
              %li
                - current_user.projects.each do |project|
                  %a{:href => project_path(project)}
                    = project.name
                %a{:href => new_project_path} New Project
          %li
            %a{:href => users_path} Users

        .ul-nav.navbar-nav.navbar-right.nav
          - if current_user
            %li
              = link_to "#{current_user.full_name}", user_path(current_user)
            %li
              = link_to "Sign Out", signout_path
          - else
            %li
              = link_to "Sign Up", signup_path
            %li
              = link_to "Sign In", signin_path
    .container

      - flash.each do |type, message|
        - if type == "notice"
          %b
            %center
              .alert.alert-success= message
        - elsif type == "alert"
          %b
            %center
              .alert.alert-danger= message.html_safe

      = yield

    .container
      .page-footer
        .row
          .col-xs-offset-4.col-xs-6

            %a.button{:href => "/about"} About
            |
            = link_to "Terms", terms_path
            |
            %a.button{:href => "/faq"} FAQ
            |
            -# %a.button{:href => "/tasks"} Tasks
            -# |
            = link_to "Users", users_path
            |
            = link_to "Projects", projects_path